#Algorithm Parameters
TRAINING_FRAMES=50000000
MINIBATCH_SIZE=32
REPLAY_CAPACITY=1000000
HIST_LEN=4
TGT_UPDATE_FREQ=10000
DISCOUNT=0.99
ACT_REPEAT=4
UPDATE_FREQ=4
LEARNING_RATE=0.00025
INITIAL_EPSILON=1.0
FINAL_EPSILON=0.1
FINAL_EXPLORATION_FRAME=1000000
REPLAY_START_SIZE=50000
NO_OP_MAX=30
GRADIENT_MOMENTUM=0.95
SQUARED_GRADIENT_MOMENTUM=0.95
MIN_SQUARED_GRADIENT=0.01
TEST_EPSILON = 0.05
#Extra
NUM_THREADS=4
#Files
NUM_FRAMES_FILE="framecount.npy"
MEMORY_FILE="memory.npy"
EPSILON_FILE="epsilon.npy"
REWARD_HIST_FILE="reward_hist.npy"
CHECKPOINT_DIR="checkpoints"
#Checkpoint info
CHECKPOINT_FREQUENCY=10000

##Saving Memory, Epsilon, Episodes, training info etc.
#After how many frames should we save
TRAIN_SAVE_FREQUENCY=500000
#After how much time should we save
TRAIN_TIME_SAVE_FREQUENCY=39600
#Either save after a certain amount of time or a certain amount of frames
SAVE_ON_TIME=True
EXIT_ON_SAVE=True

#Evaluation Parameters
EVAL_FREQ = 250000
EVAL_STEPS = 125000

